name: house_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Regular.ttf
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700

  uses-material-design: true
